lib/afc_web/router.ex
defmodule AfcWeb.Router do
  use AfcWeb, :router
  import AfcWeb.Auth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug AfcWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AfcWeb do
    pipe_through :browser # Use the default browser stack

    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/", AfcWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/emotion", EmotionController, only: [:show, :create]
    resources "/info", InfoController, only: [:show]
    get "/log", LogController, :index
    get "/weekly-log", WeeklyLogController, :index
    get "/monthly-log", MonthlyLogController, :index
    resources "/share", ShareController, only: [:create]
    resources "/share/report", ShareReportController, only: [:create]
    resources "/", PageController, only: [:index, :show]
  end
end

lib/afc_web/views/component_view.ex
defmodule AfcWeb.ComponentView do
  use AfcWeb, :view
end

lib/afc_web/templates/component/container.html.eex
<div class="flex items-baseline justify-center <%= @class %>">
  <img src="https://www.actionforchildren.org.uk/images/bracket-bottom-left.png" class="container-end container-left">
  <div class="dib container-mid"></div>
  <img src="https://www.actionforchildren.org.uk/images/bracket-bottom-right.png" class="container-end container-right">
</div>

lib/afc_web/templates/component/emoji_helper.html.eex
<div class="tc w4">
  <%= link to: emotion_path(@conn, :show, @page), class: "pointer link black" do %>
    <div class="ph3 center">
      <%= emoji_img_tag(static_path(@conn, src_image(@page))) %>
    </div>
    <p><%= @text %></p>
  <% end %>
</div>

lib/afc_web/templates/component/emotions_log.html.eex
<%= for [emotion, count] <- @logs do %>
<div class="pa3 flex items-center justify-center">
  <div class="w-15 v-mid">
    <%= emoji_img_tag(static_path(@conn, src_image(emotion)), [class: "db center w4-l w3"]) %>
    <span class="f5 center"><%= format_emotion_name(emotion) %></span>
  </div>
  <%= if count > 1 do %>
  <span class="w-25-l w-70 pl3 v-mid b f5 f3-l"><%= count %> times in <%= @total_days %> days </span>
  <% else %>
  <span class="w-25-l w-70 pl3 v-mid b f5 f3-l"><%= count %> time in <%= @total_days %> days </span>
  <% end %>
</div>
<% end %>

lib/afc_web/templates/component/navbar.html.eex
<div class="flex fixed bottom-0 h3 w-100 tc bg-white bt afc-b--pink z-max">
  <%= link to: page_path(@conn, :show, ""), class: "dib w-25 pointer link black" do %>
    <p class="dot mv1 center <%= display_nav_dot(@conn, "home") %>"></p>
    <img src="<%= static_path(@conn, src_image("diary")) %>" alt="" class="w1-7 mr2 center">
    <p class="">Home</p>
  <% end %>

  <%= link to: page_path(@conn, :show, "toolbox"), class: "dib w-25 pointer link black" do %>
    <p class="dot mv1 center <%= display_nav_dot(@conn, "toolbox") %>"></p>
    <img src="<%= static_path(@conn, src_image("toolbox")) %>" alt="" class="w1-7 mr2 center">
    <p class="">Toolbox</p>
  <% end %>

  <%= link to: page_path(@conn, :show, "help"), class: "dib w-25 pointer link black" do %>
    <p class="dot mv1 center <%= display_nav_dot(@conn, "help") %>"></p>
    <img src="<%= static_path(@conn, "/images/help.svg") %>" alt="" class="w1-7 mr2 center">
    <p class="afc-red">Help</p>
  <% end %>

  <%= link to: session_path(@conn, :delete, @current_user), method: "delete", class: "dib w-25 pointer link black" do %>
    <p class="dot mv1 center"></p>
    <img src="<%= static_path(@conn, src_image("logout")) %>" alt="" class="w1-7 mr2 center">
    <p class="">Log out</p>
  <% end %>
</div>

lib/afc_web/templates/component/negative_emotion_reason.html.eex
<div class="tc" id="<%= "toolbox_" <> @emotion %>">
  <%= component "container", class: "rotate-180 mb4" %>

  <p class="mv2">If you'd like to try a coping strategy to help you feel better,</p>
  <p class="mv2">you can use the Toolbox</p>
  <button type="button" class="afc-bg-pink ph3 pv2 br2 mt3 b bn flex items-center center" id="toolbox-open-btn">
    <img src="<%= static_path(@conn, src_image("toolbox")) %>" alt="" class="w2 mr2">
    <p class="">Toolbox</p>
  </button>
  <%= component "container", class: "mt2" %>

  <div class="absolute bg-white w-100 top-0 left-0 tl dn pa3" id="toolbox-modal">
    <div class="mw7 center">
      <div class="pr3 tr">
        <button type="button" class="ph3 pv2 br2 mt3 b afc-b--red ba bg-white afc-red" id="toolbox-close-btn">
          <span class="normal mr3">X</span>
          Exit
        </button>
      </div>
      <div class="mb6 mt5 f4"><%= component(pick_toolbox(@emotion), conn: @conn, id: "title-sadness") %></div>
    </div>
  </div>

</div>

<div class="">
  <div class="mv4 flex center w5-1">
    <div class="w-40 pl3 mt2">
      <%= emoji_img_tag(static_path(@conn, src_image(@emotion))) %>
    </div>
    <div class="w-60 pl3">
      <p class="mv2">I'm sorry you're feeling <%= @emotion %> today.</p>
      <p class="mv2">Now is a good time to think about why you may have felt that way</p>
    </div>
  </div>
  <p class="b tc mb3">(Select as many as you like)</p>
</div>

lib/afc_web/templates/component/positive_emotion_reason.html.eex
<div class="mv4 flex center w5-1">
  <div class="w-40 pl3 mt2">
    <%= emoji_img_tag(static_path(@conn, src_image(@emotion))) %>
  </div>
  <div class="w-60 pl3">
    <p class="mv2">That's great!</p>
    <p class="mv2">What made you <%= @emotion %> today?</p>
  </div>
</div>

lib/afc_web/templates/component/share_report_btn.html.eex
<div class="tc mt5 mb3 f4">
  <%= form_for @conn, "/share/report", fn f -> %>
    <input type="hidden" name="from" value="<%= @from %>">
    <input type="hidden" name="to" value="<%= @to %>">
    <input type="hidden" name="url" value="<%= @conn.request_path %>?<%= @conn.query_string %>&shared=true">
    <%= submit("Share with Trusted Adult", class: "b ba afc-b--red ph3 pv2 br2 bg-white pointer") %>
  <% end %>
</div>

lib/afc_web/templates/component/toolbox_anger.html.eex
<p class="b tc f4 mb3 mt5" id="<%= @id %>">Anger</p>

<div class="toolbox-shadow">
  <%= component "toolbox_label", conn: @conn, text: "Spot your warning signals", dropdown: [
    {"", "Being angry can mean anything from mild irritation to total rage! It's OK to feel angry – but when you're at your angriest, it can be difficult to calm your thoughts or to listen when others give you good advice."},
    {"", "Think about times you've been angry and see if you can spot these signs:"},
    {"1", "What happens to your breathing? Do you start to breathe faster or hold your breath?"},
    {"2", "What happens to your body? For instance, you might get very hot or a bit shaky."},
    {"3", "Do you act or think differently when you're angry? You might notice you move very quickly, or have negative thoughts."},
    {"", "Learning to spot your 'angry signs' gives you a chance to let off steam. This is really useful because it means you can be angry, but still stay in control of your actions."}
  ] %>
  <%= component "toolbox_label", conn: @conn, text: "Controlled Breathing", dropdown: [
    {"", "When you get angry, you often find you start breathing faster – but this can make you feel more angry or tense!"},
    {"", "Follow these steps to calm your breath, mind and body. As you do the exercise, try to imagine you're somewhere you'd usually feel relaxed or safe."},
    {"1", "Breathe in slowly while you count in your head: \"1, 2, 3, 4, 5\"."},
    {"2", "Hold your breath for a few seconds."},
    {"3", "Breathe out slowly, again counting to 5."},
    {"4", "Keep breathing like this until you feel calmer."}
  ] %>

  <%= component "toolbox_label", conn: @conn, text: "Burn off that energy", dropdown: [
    {"", "When you feel angry you might notice you have a lot more energy than usual. Doing something physically tiring helps burn off this energy – so it's a great way to respond to anger. "},
    {"", "Try one of these suggestions to release energy and feel calmer:"},
    {"1", "Move around! Could you go for a run? Or even run on the spot? A fast walk will also help."},
    {"2", "Tightly scrunch your toes for a few seconds then release and relax them. Gradually work your way up your body tensing and then relaxing your thighs, bottom, stomach, arms, hands, shoulders, neck and face."},
    {"3", "Talk to a friend or family member about different physical activities you could try to release your energy when you are feeling angry."}
  ] %>

  <%= component "toolbox_label", conn: @conn, text: "Write how you feel", dropdown: [
    {"", "Showing or saying how you feel can help you feel better. Writing in a diary or notebook is one way to do this."},
    {"", "Try writing or drawing:"},
    {"1", "How you feel?"},
    {"2", "What happened to make you feel like this?"},
    {"3", "What do you wish could be different?"},
    {"4", "Anything else that's on your mind?"},
    {"", "Whatever you're feeling, it's OK to write it down and let it out!"}
  ] %>
</div>

lib/afc_web/templates/component/toolbox_label.html.eex
<label>
  <input type="checkbox" id="emotion_info_checkbox" class="dn toolbox-title-section">
  <div class="pl3 flex items-center bb afc-b--pink" id="emotion-info-name-div">
    <p class="pv4 pl2 w-80 w-90-ns"><%= @text %></p>
    <div class="w-20 w-10-ns tc" id="emotion_info_arrow">
      <%= emoji_img_tag(static_path(@conn, src_image("arrow")), class: "mw1") %>
    </div>
  </div>
  <div class="dn bb afc-b--pink bw1 pb5" id="emotion_info_more">
    <div class="w-90 center">
      <%= for {num, text} <- @dropdown do %>
        <%= component "toolbox_reason", num: num, text: text %>
      <% end %>
    </div>
  </div>
</label>

lib/afc_web/templates/component/toolbox_link.html.eex
<div class="ph4 flex items-center pb2 bb afc-b--pink mb2">
  <div class="w-20 mh3 mw4 ph3-ns tc">
    <%= emoji_img_tag(static_path(@conn, src_image(@image)), class: "") %>
  </div>
  <a href="<%= @link %>" class="w-80 f4 pl3 afc-blue"><%= @link_text %></a>
</div>

lib/afc_web/templates/component/toolbox_reason.html.eex
<div class="flex mv3">
  <%= if @num == "" do %>
    <p><%= @text %></p>
  <% else %>
    <p><%= @num %>.</p>
    <p class="pl3"><%= raw @text %></p>
  <% end %>
</div>

lib/afc_web/templates/component/toolbox_sadness.html.eex
<p class="b tc f4 mb3 mt5" id="<%= @id %>">Sadness</p>

<div class="toolbox-shadow">
  <%= component "toolbox_label", conn: @conn, text: "Think positive thoughts", dropdown: [
    {"", "Sometimes we think mean thoughts about ourselves.  For example, \"I'm so clumsy, I ruin everything\" or \"I'm not clever – I'll never pass that test\"."},
    {"", "Thoughts like these drag you down, but there's a way to zap them:"},
    {"1", "First think of your best feature, or a feature you'd like to have. You might be confident, kind, sporty, friendly, creative, determined, or something completely different."},
    {"2", "Next write a positive sentence about your best feature. For example, \"I am calm and confident\", \"I am proud of the things I've done\" or \"I am a good person and I like myself!\""},
    {"", "Whenever you catch yourself thinking a mean thought, turn it around by saying your positive sentence. If you like, write your positive thought on a card and keep it where you can see it every day."}
  ] %>

  <%= component "toolbox_label", conn: @conn, text: "Make a plan", dropdown: [
    {"", "Knowing how you'll deal with tough situations can help make them less stressful. Use this list to make an action plan:"},
    {"1", "Think about the week ahead. What coming events or situations might make you feel bad?"},
    {"2", "Think of 3 things to try if you feel upset. Remember ACE: activities which give you a sense of <b>A</b>chievement, whereby you feel <b>C</b>lose to other people, and making sure you do things you <b>E</b>njoy."},
    {"3", "During the week, use your action plan to cope with the stressful situation or feeling."},
    {"4", "Review your plan at the end of the week. Which actions did you try? Which ones helped?"},
    {"", "If you find an action that works, remember to include it in next week's plan!"}
  ] %>

  <%= component "toolbox_label", conn: @conn, text: "Colour breathing", dropdown: [
    {"", "You can use this exercise to relax and let go of uncomfortable feelings. Start by sitting or lying somewhere comfortable."},
    {"1", "Choose a colour that makes you feel good – perhaps a warm, sunny yellow or calm sea blue."},
    {"2", "Now pick a colour that reminds you of the uncomfortable feelings you want to get rid of. You could choose a rainy grey or angry red for this"},
    {"3", "Close your eyes and breathe in slowly through your nose. Imagine you're breathing in your good colour. Feel it move through your chest and belly. As the colour spreads, it relaxes every bit of you."},
    {"4", "Breathe out softly through your mouth. Imagine you're blowing out the uncomfortable colour and feelings."},
    {"5", "Keep breathing in and out. Feel the good colour filling you up from your toes to the top of your head. Let the angry colours melt away."},
    {"6", "When you're ready, open your eyes and notice what you see and hear all around you."}
  ] %>

  <%= component "toolbox_label", conn: @conn, text: "Become a detective", dropdown: [
    {"", "Negative thoughts make us believe we're useless, or a failure, or that someone doesn't like us. Sometimes these thoughts happen so quickly that we don't stop to ask if they're really true. "},
    {"", "The next time you notice a negative thought, pretend you're a detective and use these steps to find the evidence:"},
    {"1", "What proof is there that your negative thought is <b>true</b>?"},
    {"2", "What evidence shows you the negative thought is <b>false</b>?"},
    {"3", "Can you be 100% sure that the negative thought is true? If not, why not?"},
    {"4", "If you're absolutely sure the negative thought is true, make a list of good things about yourself or the situation so you can see the <b>whole picture</b>."}
  ] %>

  <%= component "toolbox_label", conn: @conn, text: "Be your own bestie", dropdown: [
    {"", "For a few days, imagine you're a friend who needs looking after. Find ways to encourage yourself, just like you would support your best friend."},
    {"", "Give yourself a thumbs up or a cheer every time you try your best – even if it's not perfect."},
    {"", "It's easy to always look for your own faults. Sometimes just being a friend to yourself can take the pressure off."}
  ] %>

</div>

lib/afc_web/templates/component/toolbox_worry.html.eex
<p class="b tc f4 mb3 mt5" id="<%= @id %>">Worry</p>

<div class="toolbox-shadow">
  <%= component "toolbox_label", conn: @conn, text: "Play a distraction game", dropdown: [
    {"", "Being 'distracted' means forgetting about something for a bit. This can be useful when you can't stop having an upsetting thought."},
    {"", "When you feel worried, try one of these games to take your mind off things:"},
    {"1", "Count backwards from 50, but take away 4 each time. Start with \"50 …. 46 … 42 … 38\" and keep going."},
    {"2", "Think of a TV show you watch. Get a piece of paper and write down as many characters from the show as you can remember. Try to keep going until you've listed them all."},
    {"3", "Pick a letter of the alphabet and write 25 words that start with that letter. So if you pick the letter D, find 25 words that start with a 'D' – like <b>d</b>og, <b>d</b>ish, and <b>d</b>ancer."},
    {"", "You can make these more challenging by setting a timer. Give yourself 2 minutes to finish the game – then try to beat your score."}
  ] %>
  <%= component "toolbox_label", conn: @conn, text: "Try being mindful", dropdown: [
    {"", "When you're being 'mindful', you really pay attention to something. You can try this anywhere, whether you're walking, listening to music or tidying your room – just follow the steps below."},
    {"1", "Remind yourself what you're doing. For example, \"I'm walking to school\" or \"I'm at the bus stop\"."},
    {"2", "What can you hear, see, smell, touch or taste? Think about each sensation."},
    {"3", "What are your arms, fingers or legs doing? Are you moving quickly or slowly?"},
    {"4", "Think about your breathing. Where can you feel it – in your chest, belly or nose? Can you slow it down, so you're taking deep breaths and feeling more relaxed? "},
    {"5", "If other thoughts pop up, just notice them then gently bring your attention back to your breathing."},
    {"", "The more you practice being mindful, the easier it becomes. Try to keep it up for 5 minutes, or for as long as you like."}
  ] %>
  <%= component "toolbox_label", conn: @conn, text: "Imagine a peaceful place", dropdown: [
    {"", "Think of a place where you feel safe and comfortable. This might be somewhere you've been, but it could be a place you've seen on TV or in a picture."},
    {"", "Once you've got a place in mind, follow these steps:"},
    {"1", "Focus on the colours you can see in your safe, peaceful place."},
    {"2", "Now think about the sounds you can hear."},
    {"3", "What smells do you notice about your peaceful place?"},
    {"4", "Think about the sensations on your skin. Can you feel the wind? Do you feel hot or cold?"},
    {"5", "Give your peaceful place a name. Think of this name to return there whenever you like."},
    {"6", "Stay in your safe, peaceful place until you feel calm and relaxed. "},
    {"7", "When you're ready, open your eyes and notice what you see and hear all around you."}
  ] %>
  <%= component "toolbox_label", conn: @conn, text: "Relax every muscle", dropdown: [
    {"", "You can use this exercise to melt away unpleasant feelings. Practice these steps when you're calm to make them easier to follow along when you're anxious or worried. This is also a great way to fall asleep at night."},
    {"", "Start by sitting or lying somewhere quiet and comfortable, then work through this list:"},
    {"1", "Think about your toes. Clench your toes as hard as you can for 5 seconds, then relax them completely. "},
    {"2", "Can you feel the difference when squeezing and releasing your toes? Does it feel good when you release the tension?"},
    {"3", "Move your attention to your calves. Repeat the exercise. Clench and then release just this part of your body."},
    {"4", "One at a time squeeze and release your thighs, bottom, back, tummy, arms, shoulders and neck. Then do your mouth, eyes and forehead."},
    {"5", "Lie or sit still and enjoy the feeling of calm relaxation as long as you like."}
  ] %>

  <%= component "toolbox_label", conn: @conn, text: "Build a bubble", dropdown: [
      {"", "The 'bubble technique' can help you feel calmer or safer."},
      {"1", "Imagine you're inside a soft bubble. It's <b>your</b> bubble, so make it any colour and size you like."},
      {"2", "Fill your bubble with your favourite things: music, memories, smells and anything else that makes you feel good."},
      {"3", "Your bubble is a safe space. Imagine that someone tries to upset you but their words just bounce off the bubble without hurting you."},
      {"", "Practice the bubble technique every day if you can, even for a few minutes. After a while, you'll be able to imagine a bubble around you whenever you feel stressed."}
  ] %>
</div>

lib/afc_web/templates/component/trusted_share_btn.html.eex
<div class="tc mt5 mb3 f4">
  <%= form_for @conn, "/share", fn f -> %>
    <input type="hidden" name="emotion_log_id" value="<%= @emotion_log.id %>">
    <input type="hidden" name="date" value="<%= @date %>">
    <%= submit("Share with Trusted Adult", class: "b ba afc-b--red ph3 pv2 br2 bg-white pointer") %>
  <% end %>
</div>