lib/afc_web/router.ex
defmodule AfcWeb.Router do
  use AfcWeb, :router
  import AfcWeb.Auth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug AfcWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AfcWeb do
    pipe_through :browser # Use the default browser stack

    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/", AfcWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/emotion", EmotionController, only: [:show, :create]
    resources "/info", InfoController, only: [:show]
    get "/log", LogController, :index
    get "/weekly-log", WeeklyLogController, :index
    get "/monthly-log", MonthlyLogController, :index
    resources "/share", ShareController, only: [:create]
    resources "/share/report", ShareReportController, only: [:create]
    resources "/", PageController, only: [:index, :show]
  end
end

lib/afc_web/templates/page/help.html.eex
<div class="mb5 pv3">
  <%= component "container", class: "rotate-180 mb3" %>
  <div class="mw5 center">
    <img src="<%= static_path(@conn, src_image("siren")) %>" alt="" class="w3 db center mb3">
    <p class="mv2 b tc">If you need help now,</p>
    <p class="mt2 mb3 b tc">don't wait</p>
    <img src="<%= static_path(@conn, src_image("chat-icon")) %>" alt="" class="w2 db">
    <p class="mv2">Speak to an adult that you trust, if you would like more advice on how you are feeling.</p>
  </div>
  <%= component "container", class: "mt3" %>

  <div class="mw5 center mv4 pv2">
    <img src="<%= static_path(@conn, src_image("phone-icon")) %>" alt="" class="w2 db">
    <p class="mt2 mb3">If you don't have anyone you can talk to right now, and you need immediate support with how you're feeling.</p>
    <a href="tel:08001111" class="mv2 b underline afc-red">Call Childline on 0800 1111</a>
  </div>

  <div class="mw5 center mv4 pv2">
    <img src="<%= static_path(@conn, src_image("ambulance-icon")) %>" alt="" class="w2 db">
    <p class="mt2 mb3">If it’s an emergency and there’s a risk to your life, or anyone else’s life.</p>
    <a href="tel:999" class="mv2 b underline afc-red">Call the Police on 999</a>
  </div>
</div>

lib/afc_web/templates/page/index.html.eex
<%= component "day_week_month_bar", conn: @conn %>

<div class="pv3">
  <div class="w-90 w-60-ns bg-white center br2 pa3 mb5 mt-day-week-month">
    <p id="elm-calendar" class="pa3 ba br2 dib mb4">10th Oct 2019 (placeholder)</p>
    <p class="tc b f4 mb3">How are you feeling today?</p>
    <div class="center w-90 w-40-l">

      <div class="flex justify-between pt3 ph1 mb3">
        <%= component "emoji_helper", [text: "Happy", page: "happy", conn: @conn] %>
        <%= component "emoji_helper", [text: "Excited", page: "excited", conn: @conn] %>
      </div>

      <div class="flex justify-between pt3 ph1 mb3">
        <%= component "emoji_helper", [text: "Angry", page: "angry", conn: @conn] %>
        <%= component "emoji_helper", [text: "Sad", page: "sad", conn: @conn] %>
      </div>

      <div class="flex justify-between pt3 ph1 mb3">
        <%= component "emoji_helper", [text: "Worried", page: "worried", conn: @conn] %>
        <%= component "emoji_helper", [text: "I don't know", page: "unsure", conn: @conn] %>
      </div>

      <div class="flex justify-between pt3 ph1 mb3">
        <%= component "emoji_helper", [text: "Something else", page: "else", conn: @conn] %>
        <div class="w4"></div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  var millis = <%= @millis %>
</script>

lib/afc_web/templates/page/info.html.eex
<div class="afc-bg-dark-blue pv3">
  <p class="b white tc pt5 pb4 f4">Helpful Advice and Information</p>
</div>

<div class="bg-white mw7 center pa3 pt4 mb5 pb5">
  <div class="w-70-ns center flex mv2 pt4">
    <%= link to: info_path(@conn, :show, "what_is_mental_wellbeing"), class: "tc ma2 toolbox-shadow w-50 h4 flex afc-dark-blue" do %>
      <p class="mv3 self-center center ph2 lh-copy">What is Mental Wellbeing?</p>
    <% end %>

    <%= link to: info_path(@conn, :show, "what_affects_mental_wellbeing"), class: "tc ma2 toolbox-shadow w-50 h4 flex afc-dark-blue" do %>
      <p class="mv3 self-center center ph2 lh-copy">What affects mental wellbeing?</p>
    <% end %>
  </div>

  <div class="w-70-ns center flex mv2">
    <%= link to: info_path(@conn, :show, "what_is_change"), class: "tc ma2 toolbox-shadow w-50 h4 flex afc-dark-blue" do %>
      <p class="mv3 self-center center ph2 lh-copy">What is change?</p>
    <% end %>

    <%= link to: info_path(@conn, :show, "coping_with_change"), class: "tc ma2 toolbox-shadow w-50 h4 flex afc-dark-blue" do %>
      <p class="mv3 self-center center ph2 lh-copy">Coping with change</p>
    <% end %>
  </div>
</div>

lib/afc_web/templates/page/not_found.html.eex
<div class="pv3">
  <div class="w-90 bg-white center br2 pa3 mb5">
    <p>Page not found</p>
  </div>
</div>

lib/afc_web/templates/page/toolbox.html.eex
<div class="w-90 center pa3 pb4 tc f4 mt3">
  <p class="b mv3">This is your coping toolbox.</p>
  <p class="center ph3 mb3">Come here any time you need to practise a coping strategy.</p>
</div>

<div class="bg-white center pa3 pt4 mb5 pb5">

  <div class="mw7 center">
    <p class="pl2 pb2 lh-title mb3">Find coping strategies that work best for what you’re feeling.</p>

    <%= component "toolbox_link", conn: @conn, image: "sad", link_text: "Sadness", link: "#title-sadness" %>
    <%= component "toolbox_link", conn: @conn, image: "angry", link_text: "Anger", link: "#title-anger" %>
    <%= component "toolbox_link", conn: @conn, image: "worried", link_text: "Worry", link: "#title-worry" %>
    <%= component "toolbox_link", conn: @conn, image: "info", link_text: "More Info...", link: "/info" %>

    <%= component "toolbox_sadness", conn: @conn, id: "title-sadness" %>
    <%= component "toolbox_anger", conn: @conn, id: "title-anger" %>
    <%= component "toolbox_worry", conn: @conn, id: "title-worry" %>
  </div>

  <div class="mw7 center tc mt5">
    <%= component "container", class: "rotate-180 mb4" %>
    <p class="mb4 b afc-red f3">Speak to someone</p>
    <p class="mv2">Talk to your trusted adult</p>
    <p class="mb4">about how you're feeling</p>
    <%= component "container", class: "mt2" %>
  </div>
</div>